### ISSUE TITLE
HyperV configuration docs

### ISSUE THREAD

**Issue by jdelrue** [JimberSoftware/docs#1]
Go to settings and choose legacy instead of EFI

**Comment by danny-delrue** [comment]
Screenshots still need to be added.

**Comment by danny-delrue** [comment]
Is it necessary to explain how to install Hyper-V on a server?

**Comment by TheBoncy** [comment]
there are now 2 pages for this
- under advanced : hypervisor installation
- under devices: Network Controllers Installation (bottom of page)
the one under network controllers installation is more detailed

**Comment by danny-delrue** [comment]
Modified: in Network Controller Installation a link to the Hypervisor Installation page was added.  The detailed explanation has been removed from the Network Controller Installation page.
