### ISSUE TITLE
Weird wording when installing NC

### ISSUE THREAD

**Issue by azertyalex** [JimberSoftware/docs#11]
https://docs.jimber.io/#/./devices/networkcontrollerssetup/SettingUpServer:~:text=Then%20you%20will%20see%20a%20window%20with%20the%20message%20%E2%80%9CConfirm%20destructive%20action%E2%80%9D.%20This%20is%20a%20warning%20that%20all%20data%20on%20the%20used%20disks%20will%20be%20lost.%20Only%20in%20case%20of%20starting%20this%20process%20by%20mistake%2C%20you%20can%20choose%20here%20for%20%E2%80%9CContinue%E2%80%9D.

**Comment by danny-delrue** [comment]
Text adjusted: "In the next window you have to confirm that all data on the used disks may be lost. You can choose here for “Continue”."
