### ISSUE TITLE
credentials are not provided

### ISSUE THREAD

**Issue by azertyalex** [JimberSoftware/docs#12]
How is a user supposed to obtain username and password?

its:
username: jimber
password: jimber

https://docs.jimber.io/#/./devices/networkcontrollerssetup/SettingUpServer:~:text=Continuation%20of%20the%20installation
![Image](https://github.com/JimberSoftware/docs/assets/9082988/8ecb987d-ca38-4c22-8668-c1eb2825fa43)

**Comment by jdelrue** [comment]
The new NC asks the password at first boot, the username should be in the docs

They can download the ISO themselves so they can't get them from us, we dont know they are installing.

**Comment by danny-delrue** [comment]
Okay! Adjusted
