### ISSUE TITLE
Customers is available for integrators and distributors

### ISSUE THREAD

**Issue by JorisBassle** [JimberSoftware/docs#17]
It says the customer section is only available for Integrators, but Distributors can also create customers.

![Image](https://github.com/JimberSoftware/docs/assets/36887810/9aa2cdb5-752f-49a2-b90d-8082254e4b32)

On the 'Getting started' page and on the 'customers' page it says this:

![Image](https://github.com/JimberSoftware/docs/assets/36887810/6674bfb5-56d6-4ad1-968a-c79cf710d052)

![Image](https://github.com/JimberSoftware/docs/assets/36887810/abb653e8-db9d-4dee-902d-9478ca772be8)

**Comment by jdelrue** [comment]
Distributors shouldnt be in docs
