### ISSUE TITLE
Servers Linux Installation screenshot misplaced

### ISSUE THREAD

**Issue by TheBoncy** [JimberSoftware/docs#42]
On the Linux install guide the screenshot of the json and note about the commas is below the "edit server" screenshot instead of below the text about editing the json like it is on the Windows guide

Windows:
![Image](https://github.com/user-attachments/assets/b7fea8e4-2ffa-4671-a6f0-5c58dc7e3a85)
Linux:
![Image](https://github.com/user-attachments/assets/ab40d1d3-d605-4a29-8440-5fd95af3b0a6)

**Comment by TheBoncy** [comment]
windows guide has since changed but it is still a good example of where these screenshots should be

**Comment by danny-delrue** [comment]
Adjusted!
