### ISSUE TITLE
Synology no link to downloads

### ISSUE THREAD

**Issue by TheBoncy** [JimberSoftware/docs#55]
On the synology page when mentioning the need to download the package there is no reference to the download page like there is for the windows and linux guide.

![Image](https://github.com/user-attachments/assets/fdcdab71-14f5-4e2b-8810-f541325d803e)
![Image](https://github.com/user-attachments/assets/8aaf455b-3068-4fe7-88c8-6b1c1b34ef6a)

Additionally there is no mention that you can look for specific packages under the advanced toggle on the download page.

**Comment by danny-delrue** [comment]
Done!
