### ISSUE TITLE
LINUX SERVER - new setting UI

### ISSUE THREAD

**Issue by JorisBassle** [JimberSoftware/docs#58]
The linux server now has a new UI setting to set the token.
You can use the command jimberfw -config to use it.

This needs to be changed in the current documentation. So instead of changing the token from /etc/jimber/settings.json they can do it with the 'jimberfw -config' command.

![Image](https://github.com/user-attachments/assets/d4762626-b3a8-499c-ab02-d971f79b5cf9)

**Comment by danny-delrue** [comment]
Modified!
